name: flutter_qa_debug_tool
description: A Flutter package for debugging network requests and responses with Dio. Includes a beautiful UI for viewing logs with search, filtering, and JSON tree viewing.
version: 1.0.0
homepage: https://github.com/esnadtech/flutter_qa_debug_tool.git

environment:
  sdk: ^3.9.2
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

